routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// use App\Events\newNotifications;
// route::get('clear-all' , function (){
//     \Artisan::call('clear:all');
//     \Artisan::call('queue:work --once');
// });


Route::group([ 'prefix' => 'admin','namespace' => 'Admin','as' => 'admin.'], function () {
    Route::group(['as' => 'auth.'], function () {
        Route::get('/', ['uses' => 'Auth\LoginController@showLoginForm', 'as' => 'login.show-login-form']);
        Route::post('login', ['uses' => 'Auth\LoginController@login', 'as' => 'login.login']);
        Route::post('logout', ['uses' => 'Auth\LoginController@logout', 'as' => 'login.logout']);
    });

    Route::group(['middleware' => 'auth:admin'], function () {
        Route::get('home', ['uses' => 'HomeController@index', 'as' => 'home.index']);
        Route::get('add-product/{id}', ['uses' => 'ProductsController@index', 'as' => 'product']);
        Route::post('product-action/{id}', ['uses' => 'ProductsController@action', 'as' => 'product-action']);
        Route::get('delete-product/{id}', ['uses' => 'ProductsController@destroy', 'as' => 'delete-product']);
        Route::post('upload-image', ['uses' => 'HomeController@uploadImage', 'as' => 'upload-image']);
        Route::post('delete-image', ['uses' => 'HomeController@DeleteImage', 'as' => 'delete-image']);
    });

});

route::get('/',['uses' => 'Admin\Auth\LoginController@showLoginForm', 'as' => 'login.show-login-form' ]);

Route::get('/login',function (){

})->name('auth.login.show-login-form');

Route::group([ 'namespace' => 'Front','as' => 'front.'],function(){
    Route::get('/404',['uses' => 'IndexController@error404','as' => '404' ]);
    Route::get('/',['uses' => 'IndexController@index','as' => 'index' ]);
    route::get('/product/{slug}/detail',['uses' => 'IndexController@detail','as' => 'product.detail']);


    Route::group(['as' => 'auth.'],function (){
    Route::get('/login',['uses' => 'Auth\LoginController@showLoginForm','as' => 'login']);
    Route::post('/login',['uses' => 'Auth\LoginController@login','as' => 'login.submit']);
    Route::post('/register',['uses' => 'Auth\RegisterController@register','as' => 'register']);
    Route::get('/register',['uses' => 'Auth\RegisterController@showRegistrationForm','as' => 'register-page']);
    Route::get('/logout',['uses' => 'Auth\LoginController@logout','as' => 'logout']);
    

   });

  route::group(['middleware' => ['auth', 'cart']],function (){
      /* Add to cart routes*/
      route::post('add-to-cart',['uses' => 'CartController@add','as' => 'cart.add']);
      route::get('cart',['uses' => 'CartController@index','as' => 'cart.index']);
      route::get('get-cart-data',['uses' => 'CartController@getCart','as' => 'get-cart-data']);
      route::post('update-cart',['uses' => 'CartController@updateCart','as' => 'cart.update']);
      route::get('delete-cart/{id}',['uses' => 'CartController@deleteCart','as' => 'cart.delete']);

  });
});

app/Http/Controllers/Front/CartController.php
<?php

namespace App\Http\Controllers\Front;

use App\Models\Attribute;
use App\Models\Cart;
use App\Models\Coupon;
use App\Models\Product;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use phpDocumentor\Reflection\Types\Null_;
use Carbon\Carbon;
use App\Traits\CartTrait;


class CartController extends Controller
{
    use CartTrait;


    public function __construct() {
        $this->middleware('auth');
        parent::__construct();
    }
    
    public function add(Request $request){
        $this->validate(request(), ['product_id' => 'required | exists:products,id', 'quantity' => 'required | integer | min:1']);
        $cart = $this->addToCart($request);
        if($cart == 'supplier'){
            return back()->with('error', __('Supplier cannot use add to cart functionality'));
        }
        if($cart == 'out of stock'){
            return back()->with('error', __('Product is out of stock'));
        }
        if($cart == 'greater than stock'){
            return back()->with('error', __('Required quantity is greater than stock'));
        }
        if($cart == 'success'){
            return  redirect(route('front.cart.index'));
        }
        return back()->with('error', __('Something went wrong'));     
    }

    public  function index(){
        return view('front.cart');
    }


    public function getCart()
    {
        $cartData = $this->cartIndex();
        return json_encode($cartData);
    }



    public function updateCart(Request $request){
        $request->validate([
            'cart_id' => 'required|exists:carts,id',
            'quantity' => 'required|numeric'
        ]);
        if($request->quantity < 1)
        {
            return responseBuilder()->error(__('Please enter quantity greater than 0'));
        }
        $cart = $this->updateCartTrait($request, true);
        if ($cart == "please change quantity"){
            return responseBuilder()->error(__('Please change quantity'));
        }
        if ($cart == "greater than stock"){
            return responseBuilder()->error(__('Your Quantity Is Greater Than Stock'));
        }
        if ($cart == "success"){
            return responseBuilder()->success(__('success'));
        }
        return responseBuilder()->error(__("Something went wrong"));

    }

    public function deleteCart($id){
        $cart = $this->deleteCartTrait($id, true);
        if($cart == 'success'){
            $cartData = $this->cartIndex(true);
            return json_encode($cartData);
        }
    }

}

app/Http/Controllers/Front/IndexController.php
<?php

namespace App\Http\Controllers\Front;


use App\Http\Controllers\Controller;
use App\Http\Requests\User\UserRequest;
use App\Http\Requests\ContactUs;
use App\Http\Libraries\Uploader;
use App\Http\Services\users\UserService;
use App\Models\{Category, Page, Product, User,City};
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Traits\{EMails, SuppliersTrait, Products};
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;
use Tymon\JWTAuth\Facades\JWTAuth;

class IndexController extends Controller {
    public function __construct() {
        parent::__construct();
    }

    
    public function index() {
        $products = Product::latest('created_at')->paginate(8);
        return view('front.index',['products' => $products]);
    }

    public function detail($slug){
        $product = Product::where('slug',$slug)->first();
        return view('front.product-detail',['product' =>  $product]);
    }
    
    

    
}

resources/views/front/cart.blade.php
@extends('front.layouts.app')

@section('css')

<style>
    .card {
        height: 400px;
        margin-top: 20px !important;
        position: relative;
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-orient: vertical;
        -webkit-box-direction: normal;
        -ms-flex-direction: column;
        flex-direction: column;
        min-width: 0;
        word-wrap: break-word;
        background-color: #fff;
        background-clip: border-box;
        border: none;
        border-radius: 0.25rem;
        position: relative;
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-orient: vertical;
        -webkit-box-direction: normal;
        -ms-flex-direction: column;
        flex-direction: column;
        min-width: 0;
        word-wrap: break-word;
        background-color: #fff;
        background-clip: border-box;
        border: none;
        border-radius: 0.25rem;
    }
</style>

@endsection

@section('content')

<section class="sec-our-categories" id="app" >
        <div class="container">
            <div class="row" v-if="cart">
                  <div class="col-lg-12">
                      <div class="my-ordemt-a mt-3 mt-md-4 consume-cart-card" v-for="(data, index) in cartData">
                          <div class="row border-bottom ">
                              <div class="to-main-cart-cl">
                                  <div class="order-img d-flex ">
                                      <img v-bind:src=data.product.image alt="" class="img-fluid" i18n-alt style="height:171px; width:222px">
                                  </div>
                                  <div class="inner-car-cl">
                                      <div class="order-text">
                                          <h5 class="tittle-order" i18n>@{{data.product.title }}</h5>
                                          <ul
                                              class="d-flex  justify-content-center justify-content-md-start  order-combination">


                                              <form class="main-cart-us" method="post" action="{{ route('front.cart.update') }}">
                                                  @csrf()
                                                  <input type="hidden" value="" name="product_id">
                                                  <div class="quantity-car-btn d-flex flex-wrap flex-md-nowrap">
                                                      <div
                                                          class="input-group increment-height mb-3 mb-xl-0 d-flex align-items-center mr-2">
                                                          <button type="button" class="btn quant-btn increment-height minus" @click="addMinusQuantity('minus', index, data.id)">
                                                              -
                                                          </button>
                                                          <input type="text" name="quantity" maxlength="3" min="0"  :id="'quantity-'+index" @change="addMinusQuantity('minus', index, data.id)" class="form-control input-number text-center increment-height" v-bind:value=data.quantity>
                                                          <button type="button" class="btn quant-btn increment-height add" @click="addMinusQuantity('add', index, data.id)">
                                                              +
                                                          </button>
                                                      </div>
                                                  </div>

                                              </form>
                                              <h5 class="mb-0  GOTHICB-1 amount combination-list w-100"> {{ __('total amount')}}
                                                  :&nbsp;<span class="color-primary">
                                                  @{{data.total_price}}</span>
                                              </h5>
                                          </ul>
                                      </div>
                                      <div class="chart-delete">
                                          <span @click="deleteProduct(data.id)">
                                              <span class="badge badge-danger">Delete</span>
                                          </span>
                                      </div>
                                  </div>


                              </div>
                          </div>

                      </div>

                  </div>

                <div class="col-lg-12">
                    <div class="my-ordemt-a mt-3 mt-md-4 consume-cart-card">
                        <div class="row border-bottom ">
                            <div class="delivery-info-chart-main">
                                <ul>
                                    <li class="main-tittle-li">{{__('sub total')}}: <span class="sub-tittle-chart-span">@{{ sub_total}}</span></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>

                

                <div class="col-lg-12">
                    <div class="cart-button-main d-flex flex-column">
                        <!-- <div class="user-profile-detail-mt">
                            <button type="button" class="btn btn-primary profile-btn orange-btn float-right"> {{ __('total price')}}: @{{ sub_total }}</button>
                          </div> -->
                          <div class="user-profile-detail-mt">
                            <br>
                            <a href="javascript:void(0)" class="btn btn-primary profile-btn float-right">Continue to Checkout</a>
                          </div>
                    </div>

                </div>


            </div>
            <div class="row" v-if="cart_empty">
                <div class="col-md-12 alert alert-danger">{{ __('No record found') }}</div>
            </div>
    </section>
@endsection

@section('js')
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.19.2/axios.min.js"></script>
    <script>
        $("#overlay").fadeIn();
        $('document').ready(function(){
            $('#app').fadeIn(300);
            $('#spinner').fadeOut(300);
            $("#overlay").fadeOut(300);
        })


        var app = new Vue({
            el: '#app',
            data: {
                cart: false,
                cart_empty: false,
                cartData: null,
                vat: null,
                sub_total: null,
                shipping_total: null,
                grand_total: null,
                coupon: true,
                coupon_applied: false,
                coupon_code: null,
                coupon_percent: 0,
                coupon_amount: 0,
                coupon_expire: false,
            },
            methods:{

                deleteProduct: function(id){
                    $("#overlay").fadeIn(300);
                    axios
                    .get(window.Laravel.baseUrl+'delete-cart/'+id)
                    .then(response => {
                        if(response.data.data.length > 0){
                            this.cart = true;
                            this.cartData = response.data.data;
                            this.vat = response.data.vat;
                            this.sub_total = response.data.sub_total;
                            this.shipping_total = response.data.shipping_total;
                            this.grand_total = response.data.grand_total;
                        }
                        else{
                            this.cart = false;
                            this.cart_empty = true
                        }
                    })
                    $("#overlay").fadeOut(300);
                },

                getCart: function(){
                    axios
                    .get(window.Laravel.baseUrl+'get-cart-data')
                    .then(response => {
                        if(response.data.data.length > 0){
                            this.cart = true;
                            this.cartData = response.data.data;
                            this.sub_total = response.data.sub_total;
                        }
                        else{
                            this.cart = false;
                        }
                    })
                },

                addMinusQuantity: function(name, index, cart_id){
                    var self = this;
                    if(name == 'add'){
                        $('#quantity-'+index).val(parseInt($('#quantity-'+index).val())+parseInt(1));
                    }
                    else{
                        $('#quantity-'+index).val(parseInt($('#quantity-'+index).val())-parseInt(1));
                    }
                    
                    if(window.setTime){
                        clearTimeout(window.setTime);
                    }
                    
                    window.setTime = setTimeout(function(){
                        $("#overlay").fadeIn(300);
                        axios
                            .post(window.Laravel.baseUrl+'update-cart', {_token:window.Laravel.csrfToken, cart_id: cart_id, quantity: $('#quantity-'+index).val()})
                            .then(response => {
                                if(response.data.success == false){
                                    swal("", response.data.message, "warning");
                                }
                                self.getCart();
                            }) 
                            $("#overlay").fadeOut(300);
                    }, 1000);
                },

                couponApply: function(){
                    if(this.coupon_code == null){
                        swal("", 'Please enter coupon code', "warning");
                        return false;
                    }
                    $("#overlay").fadeIn(300);
                    axios
                    .get(window.Laravel.baseUrl+'valid-coupon/'+this.coupon_code)
                    .then(response => {
                        $("#overlay").fadeOut(300);
                        if(response.data.success == false){
                            swal("", response.data.message, "warning");
                        }
                        if(response.data.success == true){
                            swal("", response.data.message, "success");
                            this.coupon_code = null;
                            this.getCart();
                        }
                    })
                },

                couponRemove: function(){
                    var self = this;
                    $("#overlay").fadeIn(300);
                    axios
                    .get(window.Laravel.baseUrl+'remove-coupon/')
                    .then(response => {
                        $("#overlay").fadeOut(300);
                        if(response.data.success == false){
                            swal("", response.data.message, "warning");
                        }
                        if(response.data.success == true){
                            swal("", response.data.message, "success");
                            self.coupon_code = null;
                            self.coupon = true;
                            self.coupon_expire = false;
                            self.getCart();
                        }
                    })
                }
                
            },
            beforeMount(){
                this.getCart();
            },

        })
      
    </script>
@endsection

resources/views/front/index.blade.php
@extends('front.layouts.app')

@section('css')

<style>
    .card {
        height: 400px;
        margin-top: 20px !important;
        position: relative;
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-orient: vertical;
        -webkit-box-direction: normal;
        -ms-flex-direction: column;
        flex-direction: column;
        min-width: 0;
        word-wrap: break-word;
        background-color: #fff;
        background-clip: border-box;
        border: none;
        border-radius: 0.25rem;
        position: relative;
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-orient: vertical;
        -webkit-box-direction: normal;
        -ms-flex-direction: column;
        flex-direction: column;
        min-width: 0;
        word-wrap: break-word;
        background-color: #fff;
        background-clip: border-box;
        border: none;
        border-radius: 0.25rem;
    }
</style>

@endsection

@section('content')

<main class="py-4">
    <div class="container">
        <div class="row justify-content-center">
            @forelse($products as $product)
                <div class="col-md-3">
                    <div class="card" style="margin-top:20px">
                        <div class="image-box d-flex align-items-center justify-content-center">
                            <img src="{{ asset($product->image) }}" class="img-fluid" alt="...">
                        </div>
                        <div class="card-body text-center">
                            <h5 class="card-title ">{{ $product->title }}</h5>
                            <p class="card-text text-uppercase ">${{ $product->price }}</p>
                            <a href="{{ route('front.product.detail', $product->slug) }}" class="btn btn-primary text-capitalize add-to-cart">View Detail</a>
                        </div>
                        <div class="card-bottom-bg">
                        </div>
                    </div>
                </div>
            @empty
            <div class="col-md-3 alert alert-danger">No record found</div>
            @endforelse        
        </div>
        <br><br>
        {{ $products->links() }}
    </div>
</main>

@endsection

resources/views/front/login.blade.php
@extends('front.layouts.app')

@section('content')

<main class="py-4">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-8">
                        <div class="card">
                            <div class="card-header">Login</div>

                            <div class="card-body">
                                @if(session()->has('error'))
                                    <p class="alert alert-danger">{{ session('error') }}</p>
                                @endif
                                @if( $errors->any())
                                    <ul class="alert alert-danger">
                                        @foreach($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                @endif
                                <form method="POST" action="{{ route('front.auth.login.submit') }}">
                                    @csrf()
                                    <div class="form-group row">
                                        <label for="email" class="col-md-4 col-form-label text-md-right">Email</label>

                                        <div class="col-md-6">
                                            <input id="email" type="text" class="form-control " name="email" value="{{ old('email') }}" required autocomplete="email" autofocus>
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label for="password" class="col-md-4 col-form-label text-md-right">Password</label>

                                        <div class="col-md-6">
                                            <input id="password" type="password" class="form-control " name="password" required autocomplete="current-password">

                                                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <div class="col-md-6 offset-md-4">
                                            <div class="form-check">
                                                <input class="form-check-input" type="checkbox" name="remember" id="remember" >

                                                <label class="form-check-label" for="remember">
                                                    Remember Me
                                                </label>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="form-group row mb-0">
                                        <div class="col-md-8 offset-md-4">
                                            <button type="submit" class="btn btn-primary">
                                                Login
                                            </button>

                                                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>

@endsection

resources/views/front/product-detail.blade.php
@extends('front.layouts.app')

@section('css')

<style>
    .card {
        height: 400px;
        margin-top: 20px !important;
        position: relative;
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-orient: vertical;
        -webkit-box-direction: normal;
        -ms-flex-direction: column;
        flex-direction: column;
        min-width: 0;
        word-wrap: break-word;
        background-color: #fff;
        background-clip: border-box;
        border: none;
        border-radius: 0.25rem;
        position: relative;
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-orient: vertical;
        -webkit-box-direction: normal;
        -ms-flex-direction: column;
        flex-direction: column;
        min-width: 0;
        word-wrap: break-word;
        background-color: #fff;
        background-clip: border-box;
        border: none;
        border-radius: 0.25rem;
    }
</style>

@endsection

@section('content')

<main class="py-4">
    <div class="container">
        <div class="row justify-content-center">
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-md-6">
                            <img src="{{ asset($product->image) }}">
                        </div>
                        <div class="col-md-6">
                            <h3>{{ $product->title }}</h3>
                            <p>{{ $product->description }}</p>
                            <form method="post" action="{{ route('front.cart.add') }}" class="quantity-car-btn mt-4 d-flex flex-wrap flex-md-nowrap">
                                @csrf()
                                <input type="hidden" value="{{$product->id}}" name="product_id">
                                <div class="input-group increment-height mb-3 mb-xl-0 d-flex align-items-center mr-2">
                                <button type="button" class="btn quant-btn increment-height " onclick="addRemove('minus')">
                                -
                                </button>
                                <input type="text" name="quantity" maxlength="3" id="quantity" class="form-control input-number text-center increment-height" value="1">
                                <button type="button" class="btn quant-btn increment-height " onclick="addRemove('add')"  data-type="plus" data-field="">
                                +
                                </button>
                                </div>
                    
                                <div class="user-profile-detail-mt">
                                    <input type="submit" class="btn btn-primary profile-btn" value="{{__('add to cart')}}"> 
                                </div>
                            </form>
                            @if(session()->has('error'))
                                <br>
                                <p class="alert alert-danger">{{ session('error') }}</p>
                            @endif
                        </div>
                    </div>
                </div>      
        </div>
    </div>
</main>

@endsection

@section('js')
    <script>
        function addRemove(value)
        {
        if(value == 'add'){
            if($('#quantity').val() >= 100){
                $('#quantity').val(100);
                return false;
            }
            $('#quantity').val(parseInt($('#quantity').val())+parseInt(1));
        }

        if(value == 'minus'){
            if($('#quantity').val() <= 1){
                $('#quantity').val(1);
                return false;
            }
            $('#quantity').val($('#quantity').val()-1);
        }
        }
    </script>
@endsection