routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// use App\Events\newNotifications;
// route::get('clear-all' , function (){
//     \Artisan::call('clear:all');
//     \Artisan::call('queue:work --once');
// });


Route::group([ 'prefix' => 'admin','namespace' => 'Admin','as' => 'admin.'], function () {
    Route::group(['as' => 'auth.'], function () {
        Route::get('/', ['uses' => 'Auth\LoginController@showLoginForm', 'as' => 'login.show-login-form']);
        Route::post('login', ['uses' => 'Auth\LoginController@login', 'as' => 'login.login']);
        Route::post('logout', ['uses' => 'Auth\LoginController@logout', 'as' => 'login.logout']);
    });

    Route::group(['middleware' => 'auth:admin'], function () {
        Route::get('home', ['uses' => 'HomeController@index', 'as' => 'home.index']);
        Route::get('add-product/{id}', ['uses' => 'ProductsController@index', 'as' => 'product']);
        Route::post('product-action/{id}', ['uses' => 'ProductsController@action', 'as' => 'product-action']);
        Route::get('delete-product/{id}', ['uses' => 'ProductsController@destroy', 'as' => 'delete-product']);
        Route::post('upload-image', ['uses' => 'HomeController@uploadImage', 'as' => 'upload-image']);
        Route::post('delete-image', ['uses' => 'HomeController@DeleteImage', 'as' => 'delete-image']);
    });

});

route::get('/',['uses' => 'Admin\Auth\LoginController@showLoginForm', 'as' => 'login.show-login-form' ]);

Route::get('/login',function (){

})->name('auth.login.show-login-form');

Route::group([ 'namespace' => 'Front','as' => 'front.'],function(){
    Route::get('/404',['uses' => 'IndexController@error404','as' => '404' ]);
    Route::get('/',['uses' => 'IndexController@index','as' => 'index' ]);
    route::get('/product/{slug}/detail',['uses' => 'IndexController@detail','as' => 'product.detail']);


    Route::group(['as' => 'auth.'],function (){
    Route::get('/login',['uses' => 'Auth\LoginController@showLoginForm','as' => 'login']);
    Route::post('/login',['uses' => 'Auth\LoginController@login','as' => 'login.submit']);
    Route::post('/register',['uses' => 'Auth\RegisterController@register','as' => 'register']);
    Route::get('/register',['uses' => 'Auth\RegisterController@showRegistrationForm','as' => 'register-page']);
    Route::get('/logout',['uses' => 'Auth\LoginController@logout','as' => 'logout']);
    

   });

  route::group(['middleware' => ['auth', 'cart']],function (){
      /* Add to cart routes*/
      route::post('add-to-cart',['uses' => 'CartController@add','as' => 'cart.add']);
      route::get('cart',['uses' => 'CartController@index','as' => 'cart.index']);
      route::get('get-cart-data',['uses' => 'CartController@getCart','as' => 'get-cart-data']);
      route::post('update-cart',['uses' => 'CartController@updateCart','as' => 'cart.update']);
      route::get('delete-cart/{id}',['uses' => 'CartController@deleteCart','as' => 'cart.delete']);

  });
});

resources/views/admin/edit_profile.blade.php
@extends('admin.layouts.app')
@section('breadcrumb')
    @include('admin.common.breadcrumbs')
@endsection

@push('stylesheet-page-level')
@endpush

@push('script-page-level')
    @include('admin.common.upload-gallery-js-links')
    <script>
        function getAsDate(day, time)
        {
            var hours = Number(time.match(/^(\d+)/)[1]);
            var minutes = Number(time.match(/:(\d+)/)[1]);
            var AMPM = time.match(/\s(.*)$/)[1];
            if(AMPM == "pm" && hours<12) hours = hours+12;
            if(AMPM == "am" && hours==12) hours = hours-12;
            var sHours = hours.toString();
            var sMinutes = minutes.toString();
            if(hours<10) sHours = "0" + sHours;
            if(minutes<10) sMinutes = "0" + sMinutes;
            time = sHours + ":" + sMinutes + ":00";
            var d = new Date(day);
            var n = d.toISOString().substring(0,10);
            var newDate = new Date(n+"T"+time);
            return newDate;
        }
        $(document).ready(function(){
            var values = [];
            var timing = [];
            $('.company_form').submit(function(event){
//                        console.log(1);
//                event.preventDefault();
                var inputs = $('.company_form :input');
                inputs.each(function() {
                    values[this.name] = $(this).val();
                });
                var today = new Date();
                var dd = today.getDate();
                var mm = today.getMonth()+1; //January is 0!
                var yyyy = today.getFullYear();
                if(dd<10) {
                    dd = '0'+dd
                }
                if(mm<10) {
                    mm = '0'+mm
                }
                today = dd + '/' + mm + '/' + yyyy;
                for(var i=0; i<=6 ; i++){
                    timing.push({
                        'start_time' : new moment(getAsDate(today, values['timing['+i+'][start_time]'])).unix(),
                        'end_time' : new moment(getAsDate(today, values['timing['+i+'][end_time]'])).unix(),
                        'day' : values['timing['+i+'][day]'],
                        'off' : values['timing['+i+'][off]']
                    })
                }
                $('input[name=unix_timing]').val(JSON.stringify(timing));
            });
        });

        var latitude = {!! ($adminData['id'] > 0) ? ((empty($adminData['latitude']) ? 31.55460609999999 : $adminData['latitude'])) : 31.55460609999999 !!};
        var longitude = {!! ($adminData['id'] > 0) ? ((empty($adminData['longitude']) ? 74.35715809999999 : $adminData['longitude'])) : 74.35715809999999 !!};

        function initAutocomplete(mapId, searchId, long, latit) {

            var map = new google.maps.Map(document.getElementById(mapId), {
                center: {lat: latitude, lng: longitude},
                zoom: 13,
                mapTypeId: 'roadmap'
            });

            var marker = new google.maps.Marker({
                position: {
                    lat: latitude, lng: longitude
                },
                map: map,
                draggable: true
            });

            var searchBox = new google.maps.places.SearchBox(document.getElementById(searchId));

            google.maps.event.addListener(searchBox, 'places_changed', function () {

                var places = searchBox.getPlaces();
                var bounds = new google.maps.LatLngBounds();
                var i, place;

                for (i = 0; place = places[i]; i--) {
                    bounds.extend(place.geometry.location);
                    marker.setPosition(place.geometry.location);
                }

                map.fitBounds(bounds);
                map.setZoom(15);

            });

            google.maps.event.addListener(marker, 'position_changed', function () {

                var lat = marker.getPosition().lat();
                var lng = marker.getPosition().lng();

                document.getElementById(latit).value = lat;
                document.getElementById(long).value = lng;

            });
        }
        $(document).ready(function () {
            setTimeout(function () {
                initAutocomplete('map1', 'searchmap1', 'longitude1', 'latitude1');
            }, 400);
        });
        $('#arabic').on('click', function(){
            setTimeout(function(){
                initAutocomplete('map1', 'searchmap1', 'longitude1', 'latitude1');
            },100)
        });

        $('.companies-submit').click(function () {
            var formData = new FormData(document.forms.namedItem('company-form'));
            console.log(formData);
        });
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBNcTmnS323hh7tSQzFdwlnB4EozA3lwcA&libraries=places&callback=initAutocomplete"></script>
@endpush




@section('content')

    <div class="row">
        <div class="col-lg-2"></div>
        <div class="col-lg-8">
            <div class="m-portlet m-portlet--full-height m-portlet--tabs  ">
                <div class="m-portlet__head">
                    <div class="m-portlet__head-tools">
                        <ul class="nav nav-tabs m-tabs m-tabs-line   m-tabs-line--left m-tabs-line--primary" role="tablist">
                            <li class="nav-item m-tabs__item">
                                <a class="nav-link m-tabs__link active" data-toggle="tab" href="#m_user_profile_tab_1" role="tab">
                                    <i class="flaticon-share m--hide"></i>
                                    Edit Profile
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>

                <div class="tab-content">
                    <div class="tab-pane active" id="m_user_profile_tab_1">
                        {!! Form::model($adminData, ['route' => 'admin.home.update-profile', 'method' => 'post', 'role' => 'form', 'class' => 'm-form m-form--fit m-form--label-align-right', 'enctype' => 'multipart/form-data']) !!}
                        <div class="m-portlet__body">
                            <div class="form-group m-form__group row">
                                <label for="example-text-input" class="col-3 col-form-label">
                                    {!! __('Full Name') !!}
                                    <span class="text-danger">*</span>
                                </label>
                                <div class="col-7">
                                    {!! Form::text('full_name', old('full_name'), ['class' => 'form-control', 'id' => 'full_name', 'placeholder' => __('Full Name'), 'required' => 'required']) !!}
                                </div>
                            </div>

                            <div class="form-group m-form__group row">
                                <label for="example-text-input" class="col-3 col-form-label">
                                    {!! __('Username') !!}
                                    <span class="text-danger">*</span>
                                </label>
                                <div class="col-7">
                                    {!! Form::text('user_name', old('user_name'), ['class' => 'form-control', 'id' => 'user_name', 'placeholder' => __('Username'), 'required' => 'required']) !!}
                                </div>
                            </div>

                            <div class="form-group m-form__group row">
                                <label for="example-text-input" class="col-3 col-form-label">
                                    {!! __('Email') !!}
                                    <span class="text-danger">*</span>
                                </label>
                                <div class="col-7">
                                    {!! Form::text('email', old('email'), ['class' => 'form-control', 'id' => 'email', 'placeholder' => __('Email'), 'required' => 'required']) !!}
                                </div>
                            </div>

                            <div class="form-group m-form__group row">
                                <label for="example-text-input" class="col-3 col-form-label">
                                    {!! __('Password') !!}
                                    <span class="text-danger">*</span>
                                </label>
                                <div class="col-7">
                                    {!! Form::password('password', ['class' => 'form-control', 'id' => 'password', 'placeholder' => __('Password')]) !!}
                                </div>
                            </div>

                            <div class="form-group m-form__group row">
                                <label for="example-text-input" class="col-3 col-form-label">
                                    {!! __('Confirm Password') !!}
                                    <span class="text-danger">*</span>
                                </label>
                                <div class="col-7">
                                    {!! Form::password('password_confirmation', ['class' => 'form-control', 'id' => 'password_confirmation', 'placeholder' => __('Password Confirmation')]) !!}
                                </div>
                            </div>

                            <!-- <div class="form-group m-form__group row">
                                <label for="example-text-input" class="col-3 col-form-label">
                                    {!! __('Address') !!}
                                    <span class="text-danger">*</span>
                                </label>
                                <div class="col-7">

                                    {!! Form::text('address', old('address', $adminData['address']), ['class' => 'form-control', 'placeholder' => 'Address', 'id'=>'searchmap'.$languageId]) !!}
                                    {!! Form::hidden('longitude', old('longitude', $adminData['longitude']), ['class' => 'form-control', 'placeholder' => 'Address', 'id'=>'longitude'.$languageId]) !!}
                                    {!! Form::hidden('latitude', old('latitude', $adminData['latitude']), ['class' => 'form-control', 'placeholder' => 'Address', 'id'=>'latitude'.$languageId]) !!}
                                </div>
                            </div>
                            <div class="form-group m-form__group row">
                                <label for="example-text-input" class="col-3 col-form-label">
                                    {!! __('Change Position') !!}
                                    <span class="text-danger">*</span>
                                </label>
                                <div class="col-7">
                                    <div id="map{!! $languageId !!}" style="height:500px; width:auto;margin-top: 48px"></div>
                                </div>
                            </div> -->
                            <div class="form-group m-form__group row">
                                <label for="example-text-input" class="col-3 col-form-label">
                                    {!! __('Image') !!}
                                    <span class="text-danger">*</span>

                                </label>
                                <div class="col-7">
                                    <input type="file" name="image" id="image" class="form-control">
                                </div>
                            </div>

                                <div class="form-group m-form__group row">
                                    <label for="example-text-input" class="col-3 col-form-label">
                                    Current Image
                                    </label>
                                    <div class="col-3" style="padding-top: 140px">
                                    <div class="d-flex justify-content-center align-items-center">
                                        <img style="width:120px;height: 120px; " src="{!! imageUrl(url($adminData['profile_pic']), 120, 120, 100, 1) !!}" id="image" class="selected-image img-fluid" name="image">
                                        </div>
                                        <span class="mx-2 smaller-font-size text-danger">Recommended size 120  x 120</span>
                                    </div>

                                </div>
                        </div>
                        <div class="m-portlet__foot m-portlet__foot--fit">
                            <div class="m-form__actions">
                                <div class="row">
                                    <input type="hidden" value="PUT" name="_method">
                                    <div class="col-4"></div>
                                    <div class="col-7">
                                        <button type="submit" class="btn btn-accent m-btn m-btn--air m-btn--custom">
                                            Save changes
                                        </button>
                                        &nbsp;&nbsp;
                                    </div>
                                </div>
                            </div>
                        </div>


                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/home.blade.php
@extends('admin.layouts.app')

@section('css')

<style>
    .card {
        height: 400px;
        margin-top: 20px !important;
        position: relative;
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-orient: vertical;
        -webkit-box-direction: normal;
        -ms-flex-direction: column;
        flex-direction: column;
        min-width: 0;
        word-wrap: break-word;
        background-color: #fff;
        background-clip: border-box;
        border: none;
        border-radius: 0.25rem;
        position: relative;
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-orient: vertical;
        -webkit-box-direction: normal;
        -ms-flex-direction: column;
        flex-direction: column;
        min-width: 0;
        word-wrap: break-word;
        background-color: #fff;
        background-clip: border-box;
        border: none;
        border-radius: 0.25rem;
    }
</style>

@endsection

@section('content')

<main class="py-4">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-10">
                        @if(session()->has('success'))
                            <p class="alert alert-success">{{ session('success') }}</p>
                        @endif
                        @if(session()->has('error'))
                            <p class="alert alert-danger">{{ session('error') }}</p>
                        @endif
                        <div class="card">
                            <div class="card-header">
                                <a href="{{ route('admin.product', 0) }}" class="btn btn-primary">Add Product</a>
                            </div>
                            <div class="card-body">
                               <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <td>#</td>
                                            <td>Title</td>
                                            <td>Description</td>
                                            <td>Quantity</td>
                                            <td>Price</td>
                                            <td colspan="2">Action</td>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @forelse($products as $product)
                                            <tr>
                                                <td>{{ $loop->iteration }}</td>
                                                <td>{{ $product->title }}</td>
                                                <td>{{ $product->description }}</td>
                                                <td>{{ $product->quantity}}</td>
                                                <td>{{ $product->price}}</td>
                                                <td><a href="{{ route('admin.product', $product->id) }}" class="badge badge-success">Edit</a></td>
                                                <td><a href="{{ route('admin.delete-product', $product->id) }}" onclick="return confirm('Are you sure ?') " class="badge badge-warning">Delete</a></td>
                                            </tr>
                                        @empty

                                        @endforelse
                                    </tbody>
                               </table>
                               {{ $products->links() }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>

@endsection

resources/views/admin/login.blade.php
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="Lnwjav0d2mulh3anG78G6wASpt5I3tBWG1eT5vMW">

    <title>Cart-System</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
</head>
<style>
    .span{

    }
    .badge-info{
            box-shadow: 2px 6px 5px 0px #0303;
            cursor: pointer;
    }
    .badge-success{
            box-shadow: 2px 6px 5px 0px #0303;
            cursor: pointer;
    }
    .badge-primary{
            box-shadow: 2px 6px 5px 0px #0303;
            cursor: pointer;
    }
    .badge-danger{
            box-shadow: 2px 6px 5px 0px #0303;
            cursor: pointer;
    }
    .badge-warning{
            box-shadow: 2px 6px 5px 0px #0303;
            cursor: pointer;
    }
    .card{
        box-shadow: 21px 27px 24px -22px #0303;
    }
    .custom-message{
        position: fixed;
        top: 80px;
        right: 10px;
        width: 36%;
        height: 81px;
        line-height: 3;
        box-shadow: 5px 11px 11px 0px #0303;
        z-index: 100;
        display: none;
    }
    .dropdown:hover .dropdown-menu {
        display: block;
        margin-top: 0; // remove the gap so it doesn't close
    }
    .checkbox-span{
        cursor: pointer;
    }
    #overlay{	
            position: fixed;
            top: 0;
            z-index: 100;
            width: 100%;
            height:100%;
            display: none;
            background: rgba(0,0,0,0.6);
        }
        .cv-spinner {
            height: 100%;
            display: flex;
            justify-content: center;
            align-items: center;  
        }
        .spinner {
            width: 40px;
            height: 40px;
            border: 4px #ddd solid;
            border-top: 4px #2e93e6 solid;
            border-radius: 50%;
            animation: sp-anime 0.8s infinite linear;
        }
        @keyframes sp-anime {
            100% { 
                transform: rotate(360deg); 
            }
        }
        .is-hide{
            display:none;
        }
</style>
<body>
<div id="overlay">
        <div class="cv-spinner">
            <span class="spinner"></span>
        </div>
    </div>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm" style="border-bottom:solid 1px #0303">
            <div class="container-fluid">
                <a class="navbar-brand" href="{{ route('front.index') }}">
                    Cart-System
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">

                    <!-- Right Side Of Navbar -->
                </div>
            </div>
        </nav>
        <main class="py-4">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-8">
                        <div class="card">
                            <div class="card-header">Login</div>

                            <div class="card-body">
                                @if(session()->has('error'))
                                    <p class="alert alert-danger">{{ session('error') }}</p>
                                @endif
                                @if( $errors->any())
                                    <ul class="alert alert-danger">
                                        @foreach($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                @endif
                                <form method="POST" action="{{ route('admin.auth.login.login') }}">
                                    @csrf()
                                    <div class="form-group row">
                                        <label for="email" class="col-md-4 col-form-label text-md-right">Email</label>

                                        <div class="col-md-6">
                                            <input id="email" type="text" class="form-control " name="email" value="{{ old('email') }}" required autocomplete="email" autofocus>
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label for="password" class="col-md-4 col-form-label text-md-right">Password</label>

                                        <div class="col-md-6">
                                            <input id="password" type="password" class="form-control " name="password" required autocomplete="current-password">

                                                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <div class="col-md-6 offset-md-4">
                                            <div class="form-check">
                                                <input class="form-check-input" type="checkbox" name="remember" id="remember" >

                                                <label class="form-check-label" for="remember">
                                                    Remember Me
                                                </label>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="form-group row mb-0">
                                        <div class="col-md-8 offset-md-4">
                                            <button type="submit" class="btn btn-primary">
                                                Login
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
    <!-- Scripts -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script><script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.bundle.min.js"></script>
</body>
</html>