routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// use App\Events\newNotifications;
// route::get('clear-all' , function (){
//     \Artisan::call('clear:all');
//     \Artisan::call('queue:work --once');
// });


Route::group([ 'prefix' => 'admin','namespace' => 'Admin','as' => 'admin.'], function () {
    Route::group(['as' => 'auth.'], function () {
        Route::get('/', ['uses' => 'Auth\LoginController@showLoginForm', 'as' => 'login.show-login-form']);
        Route::post('login', ['uses' => 'Auth\LoginController@login', 'as' => 'login.login']);
        Route::post('logout', ['uses' => 'Auth\LoginController@logout', 'as' => 'login.logout']);
    });

    Route::group(['middleware' => 'auth:admin'], function () {
        Route::get('home', ['uses' => 'HomeController@index', 'as' => 'home.index']);
        Route::get('add-product/{id}', ['uses' => 'ProductsController@index', 'as' => 'product']);
        Route::post('product-action/{id}', ['uses' => 'ProductsController@action', 'as' => 'product-action']);
        Route::get('delete-product/{id}', ['uses' => 'ProductsController@destroy', 'as' => 'delete-product']);
        Route::post('upload-image', ['uses' => 'HomeController@uploadImage', 'as' => 'upload-image']);
        Route::post('delete-image', ['uses' => 'HomeController@DeleteImage', 'as' => 'delete-image']);
    });

});

route::get('/',['uses' => 'Admin\Auth\LoginController@showLoginForm', 'as' => 'login.show-login-form' ]);

Route::get('/login',function (){

})->name('auth.login.show-login-form');

Route::group([ 'namespace' => 'Front','as' => 'front.'],function(){
    Route::get('/404',['uses' => 'IndexController@error404','as' => '404' ]);
    Route::get('/',['uses' => 'IndexController@index','as' => 'index' ]);
    route::get('/product/{slug}/detail',['uses' => 'IndexController@detail','as' => 'product.detail']);


    Route::group(['as' => 'auth.'],function (){
    Route::get('/login',['uses' => 'Auth\LoginController@showLoginForm','as' => 'login']);
    Route::post('/login',['uses' => 'Auth\LoginController@login','as' => 'login.submit']);
    Route::post('/register',['uses' => 'Auth\RegisterController@register','as' => 'register']);
    Route::get('/register',['uses' => 'Auth\RegisterController@showRegistrationForm','as' => 'register-page']);
    Route::get('/logout',['uses' => 'Auth\LoginController@logout','as' => 'logout']);
    

   });

  route::group(['middleware' => ['auth', 'cart']],function (){
      /* Add to cart routes*/
      route::post('add-to-cart',['uses' => 'CartController@add','as' => 'cart.add']);
      route::get('cart',['uses' => 'CartController@index','as' => 'cart.index']);
      route::get('get-cart-data',['uses' => 'CartController@getCart','as' => 'get-cart-data']);
      route::post('update-cart',['uses' => 'CartController@updateCart','as' => 'cart.update']);
      route::get('delete-cart/{id}',['uses' => 'CartController@deleteCart','as' => 'cart.delete']);

  });
});

app/Http/Controllers/Front/CartController.php
<?php

namespace App\Http\Controllers\Front;

use App\Models\Attribute;
use App\Models\Cart;
use App\Models\Coupon;
use App\Models\Product;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use phpDocumentor\Reflection\Types\Null_;
use Carbon\Carbon;
use App\Traits\CartTrait;


class CartController extends Controller
{
    use CartTrait;


    public function __construct() {
        $this->middleware('auth');
        parent::__construct();
    }
    
    public function add(Request $request){
        $this->validate(request(), ['product_id' => 'required | exists:products,id', 'quantity' => 'required | integer | min:1']);
        $cart = $this->addToCart($request);
        if($cart == 'supplier'){
            return back()->with('error', __('Supplier cannot use add to cart functionality'));
        }
        if($cart == 'out of stock'){
            return back()->with('error', __('Product is out of stock'));
        }
        if($cart == 'greater than stock'){
            return back()->with('error', __('Required quantity is greater than stock'));
        }
        if($cart == 'success'){
            return  redirect(route('front.cart.index'));
        }
        return back()->with('error', __('Something went wrong'));     
    }

    public  function index(){
        return view('front.cart');
    }


    public function getCart()
    {
        $cartData = $this->cartIndex();
        return json_encode($cartData);
    }



    public function updateCart(Request $request){
        $request->validate([
            'cart_id' => 'required|exists:carts,id',
            'quantity' => 'required|numeric'
        ]);
        if($request->quantity < 1)
        {
            return responseBuilder()->error(__('Please enter quantity greater than 0'));
        }
        $cart = $this->updateCartTrait($request, true);
        if ($cart == "please change quantity"){
            return responseBuilder()->error(__('Please change quantity'));
        }
        if ($cart == "greater than stock"){
            return responseBuilder()->error(__('Your Quantity Is Greater Than Stock'));
        }
        if ($cart == "success"){
            return responseBuilder()->success(__('success'));
        }
        return responseBuilder()->error(__("Something went wrong"));

    }

    public function deleteCart($id){
        $cart = $this->deleteCartTrait($id, true);
        if($cart == 'success'){
            $cartData = $this->cartIndex(true);
            return json_encode($cartData);
        }
    }

}

app/Http/Controllers/Front/IndexController.php
<?php

namespace App\Http\Controllers\Front;


use App\Http\Controllers\Controller;
use App\Http\Requests\User\UserRequest;
use App\Http\Requests\ContactUs;
use App\Http\Libraries\Uploader;
use App\Http\Services\users\UserService;
use App\Models\{Category, Page, Product, User,City};
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Traits\{EMails, SuppliersTrait, Products};
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;
use Tymon\JWTAuth\Facades\JWTAuth;

class IndexController extends Controller {
    public function __construct() {
        parent::__construct();
    }

    
    public function index() {
        $products = Product::latest('created_at')->paginate(8);
        return view('front.index',['products' => $products]);
    }

    public function detail($slug){
        $product = Product::where('slug',$slug)->first();
        return view('front.product-detail',['product' =>  $product]);
    }
    
    

    
}

resources/views/front/layouts/app.blade.php
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="Lnwjav0d2mulh3anG78G6wASpt5I3tBWG1eT5vMW">

    <title>Cart-System</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
</head>
<style>
    .span{

    }
    .badge-info{
            box-shadow: 2px 6px 5px 0px #0303;
            cursor: pointer;
    }
    .badge-success{
            box-shadow: 2px 6px 5px 0px #0303;
            cursor: pointer;
    }
    .badge-primary{
            box-shadow: 2px 6px 5px 0px #0303;
            cursor: pointer;
    }
    .badge-danger{
            box-shadow: 2px 6px 5px 0px #0303;
            cursor: pointer;
    }
    .badge-warning{
            box-shadow: 2px 6px 5px 0px #0303;
            cursor: pointer;
    }
    .card{
        box-shadow: 21px 27px 24px -22px #0303;
    }
    .custom-message{
        position: fixed;
        top: 80px;
        right: 10px;
        width: 36%;
        height: 81px;
        line-height: 3;
        box-shadow: 5px 11px 11px 0px #0303;
        z-index: 100;
        display: none;
    }
    .dropdown:hover .dropdown-menu {
        display: block;
        margin-top: 0; // remove the gap so it doesn't close
    }
    .checkbox-span{
        cursor: pointer;
    }
    #overlay{	
            position: fixed;
            top: 0;
            z-index: 100;
            width: 100%;
            height:100%;
            display: none;
            background: rgba(0,0,0,0.6);
        }
        .cv-spinner {
            height: 100%;
            display: flex;
            justify-content: center;
            align-items: center;  
        }
        .spinner {
            width: 40px;
            height: 40px;
            border: 4px #ddd solid;
            border-top: 4px #2e93e6 solid;
            border-radius: 50%;
            animation: sp-anime 0.8s infinite linear;
        }
        @keyframes sp-anime {
            100% { 
                transform: rotate(360deg); 
            }
        }
        .is-hide{
            display:none;
        }
</style>
<body>
<div id="overlay">
        <div class="cv-spinner">
            <span class="spinner"></span>
        </div>
    </div>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm" style="border-bottom:solid 1px #0303">
            <div class="container-fluid">
                <a class="navbar-brand" href="{{ route('front.index') }}">
                    Cart-System
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        @if($user != NULL)
                            @if($user->is_supplier == 1)
                                <a class="nav-link" href="javascript:void(0)">{{ $user->supplier_name}}</a>
                            @else
                                <a class="nav-link" href="{{ route('front.cart.index') }}">Cart <span class="badge badge-success">{{session('cart')}}</span></a>
                                <a class="nav-link" href="javascript:void(0)">{{ $user->first_name.' '.$user->last_name}}</a>
                            @endif    
                                <a class="nav-link" href="{{route('front.auth.logout')}}" >Logout</a>
                        @else
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('front.auth.login') }}">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('front.auth.register') }}">Register</a>
                            </li>
                        @endif    
                    </ul>
                </div>
            </div>
        </nav>
        @yield('content')
    </div>
    <!-- Scripts -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script><script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.bundle.min.js"></script>
    <script>
        window.Laravel = {!! json_encode([
                    'csrfToken' => csrf_token(),
                    'baseUrl' => url('/').'/'.config('app.locale')."/"/*url(config('app.locale')).'/'*/,
                    'apiUrl' => url('/').'/'.config('app.locale')."/api/"/*url(config('app.locale')).'/'*/,
                    'base' => url('/').'/',
                    'locale' => config('app.locale'),
                    'user_id' => $user['id'],
                    'currency' => $currency,
                    //  'authorization' => $user['token']

                ]) !!};
    </script>
    @yield('js')
</body>
</html>