routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// use App\Events\newNotifications;
// route::get('clear-all' , function (){
//     \Artisan::call('clear:all');
//     \Artisan::call('queue:work --once');
// });


Route::group([ 'prefix' => 'admin','namespace' => 'Admin','as' => 'admin.'], function () {
    Route::group(['as' => 'auth.'], function () {
        Route::get('/', ['uses' => 'Auth\LoginController@showLoginForm', 'as' => 'login.show-login-form']);
        Route::post('login', ['uses' => 'Auth\LoginController@login', 'as' => 'login.login']);
        Route::post('logout', ['uses' => 'Auth\LoginController@logout', 'as' => 'login.logout']);
    });

    Route::group(['middleware' => 'auth:admin'], function () {
        Route::get('home', ['uses' => 'HomeController@index', 'as' => 'home.index']);
        Route::get('add-product/{id}', ['uses' => 'ProductsController@index', 'as' => 'product']);
        Route::post('product-action/{id}', ['uses' => 'ProductsController@action', 'as' => 'product-action']);
        Route::get('delete-product/{id}', ['uses' => 'ProductsController@destroy', 'as' => 'delete-product']);
        Route::post('upload-image', ['uses' => 'HomeController@uploadImage', 'as' => 'upload-image']);
        Route::post('delete-image', ['uses' => 'HomeController@DeleteImage', 'as' => 'delete-image']);
    });

});

route::get('/',['uses' => 'Admin\Auth\LoginController@showLoginForm', 'as' => 'login.show-login-form' ]);

Route::get('/login',function (){

})->name('auth.login.show-login-form');

Route::group([ 'namespace' => 'Front','as' => 'front.'],function(){
    Route::get('/404',['uses' => 'IndexController@error404','as' => '404' ]);
    Route::get('/',['uses' => 'IndexController@index','as' => 'index' ]);
    route::get('/product/{slug}/detail',['uses' => 'IndexController@detail','as' => 'product.detail']);


    Route::group(['as' => 'auth.'],function (){
    Route::get('/login',['uses' => 'Auth\LoginController@showLoginForm','as' => 'login']);
    Route::post('/login',['uses' => 'Auth\LoginController@login','as' => 'login.submit']);
    Route::post('/register',['uses' => 'Auth\RegisterController@register','as' => 'register']);
    Route::get('/register',['uses' => 'Auth\RegisterController@showRegistrationForm','as' => 'register-page']);
    Route::get('/logout',['uses' => 'Auth\LoginController@logout','as' => 'logout']);
    

   });

  route::group(['middleware' => ['auth', 'cart']],function (){
      /* Add to cart routes*/
      route::post('add-to-cart',['uses' => 'CartController@add','as' => 'cart.add']);
      route::get('cart',['uses' => 'CartController@index','as' => 'cart.index']);
      route::get('get-cart-data',['uses' => 'CartController@getCart','as' => 'get-cart-data']);
      route::post('update-cart',['uses' => 'CartController@updateCart','as' => 'cart.update']);
      route::get('delete-cart/{id}',['uses' => 'CartController@deleteCart','as' => 'cart.delete']);

  });
});

resources/views/admin/layouts/app.blade.php
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="Lnwjav0d2mulh3anG78G6wASpt5I3tBWG1eT5vMW">

    <title>Cart-System</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
</head>
<style>
    .span{

    }
    .badge-info{
            box-shadow: 2px 6px 5px 0px #0303;
            cursor: pointer;
    }
    .badge-success{
            box-shadow: 2px 6px 5px 0px #0303;
            cursor: pointer;
    }
    .badge-primary{
            box-shadow: 2px 6px 5px 0px #0303;
            cursor: pointer;
    }
    .badge-danger{
            box-shadow: 2px 6px 5px 0px #0303;
            cursor: pointer;
    }
    .badge-warning{
            box-shadow: 2px 6px 5px 0px #0303;
            cursor: pointer;
    }
    .card{
        box-shadow: 21px 27px 24px -22px #0303;
    }
    .custom-message{
        position: fixed;
        top: 80px;
        right: 10px;
        width: 36%;
        height: 81px;
        line-height: 3;
        box-shadow: 5px 11px 11px 0px #0303;
        z-index: 100;
        display: none;
    }
    .dropdown:hover .dropdown-menu {
        display: block;
        margin-top: 0; // remove the gap so it doesn't close
    }
    .checkbox-span{
        cursor: pointer;
    }
    #overlay{	
            position: fixed;
            top: 0;
            z-index: 100;
            width: 100%;
            height:100%;
            display: none;
            background: rgba(0,0,0,0.6);
        }
        .cv-spinner {
            height: 100%;
            display: flex;
            justify-content: center;
            align-items: center;  
        }
        .spinner {
            width: 40px;
            height: 40px;
            border: 4px #ddd solid;
            border-top: 4px #2e93e6 solid;
            border-radius: 50%;
            animation: sp-anime 0.8s infinite linear;
        }
        @keyframes sp-anime {
            100% { 
                transform: rotate(360deg); 
            }
        }
        .is-hide{
            display:none;
        }
</style>
<body>
<div id="overlay">
        <div class="cv-spinner">
            <span class="spinner"></span>
        </div>
    </div>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm" style="border-bottom:solid 1px #0303">
            <div class="container-fluid">
                <a class="navbar-brand" href="{{ route('admin.home.index') }}">
                    Admin
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">

                    <!-- Right Side Of Navbar -->
                    <a href="{!! route('admin.auth.login.logout') !!}"
                        onclick="event.preventDefault();document.getElementById('logout-form').submit();" class="btn m-btn--pill    btn-secondary m-btn m-btn--custom m-btn--label-brand m-btn--bolder">
                        Logout
                        <form id="logout-form" action="{!! route('admin.auth.login.logout') !!}" method="POST" style="display: none;">
                            {!! csrf_field() !!}
                        </form>
                    </a>
                </div>
            </div>
        </nav>
        @yield('content')
    </div>
    <!-- Scripts -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script><script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.bundle.min.js"></script>
    >
    @yield('js')
</body>
</html>

resources/views/admin/layouts/auth.blade.php
<!DOCTYPE html>
<html lang="{!! config('app.locale') !!}">
    <head>
        <title>{!! __(config('settings.company_name')) !!}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="shortcut icon" href="{!! asset('assets/img/favicon.Ico') !!}" />
        <!-- Bootstrap -->
        <!-- global css -->
        <link href="{!! asset('assets/admin/css/app.css') !!}" rel="stylesheet" type="text/css">
        <!-- end of global css -->
        @stack('stylesheet-page-level')
        <style type="text/css">
            html {
                background: #313e4b !important;
            }
        </style>
        <script>var baseUrl = '{!! url("/") !!}/';</script>
    </head>
    <body>
        <div class="preloader">
            <div class="loader_img"><img src="{!! asset('assets/admin/media/loader.gif') !!}" alt="loading..." height="64" width="64"></div>
        </div>
        @yield('content')
        <!-- global js -->
        <script src="{!! asset('assets/admin/js/jquery-1.11.3.min.js') !!}" type="text/javascript"></script>
        <script src="{!! asset('assets/admin/js/bootstrap.min.js') !!}" type="text/javascript"></script>
        <!--<script src="{!! asset('assets/admin/js/backstretch.js') !!}" type="text/javascript"></script>-->
        <!-- end of global js -->
        @stack('script-page-level')
        <script type="text/javascript">
            $(document).ready(function () {
                $(window).on('load', function () {
                    $('.preloader img').fadeOut();
                    $('.preloader').fadeOut();
                });
                if ($('.bg-slider').backstretch) {
//                    $('.bg-slider').backstretch([
//                        baseUrl+"assets/img/pages/lbg-1.jpg", 
//                        baseUrl+"assets/img/pages/lbg-2.jpg", 
//                        baseUrl+"assets/img/pages/lbg-3.jpg"
//                    ], {
//                        duration: 2500,
//                        fade: 1050
//                    });
                }
                $('input').iCheck({
                    checkboxClass: 'icheckbox_minimal-blue',
                    radioClass: 'iradio_minimal-blue',
                    increaseArea: '20%' // optional
                });
            });
        </script>
    </body>
</html>

resources/views/admin/layouts/login.blade.php
<!DOCTYPE html>
<html lang="en" >
<head>
    <meta charset="utf-8" />
    <title>
        {!! config('settings.company_name') !!}
    </title>
    <meta name="description" content="Latest updates and statistic charts">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--begin::Web font -->
    <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.16/webfont.js"></script>
    <link rel="shortcut icon" href="{{asset('media/img/logo/favicon.ico')}}" />
    <script>
        WebFont.load({
            active: function() {
                sessionStorage.fonts = true;
            },
            google: {"families":["Poppins:300,400,500,600,700","Roboto:300,400,500,600,700"]}
        });
    </script>
    <link href="{{asset('assets/admin/vendors/base/vendors.bundle.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{asset('assets/admin/css/style1.bundle.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{asset('assets/admin/css/my-technology.css')}}" rel="stylesheet" type="text/css" />
    @stack('stylesheet-page-level')
</head>

<body class="m--skin- m-header--fixed m-header--fixed-mobile m-aside-left--enabled m-aside-left--skin-dark m-aside-left--offcanvas m-footer--push m-aside--offcanvas-default"  >
<!-- begin:: Page -->
<div class="m-grid m-grid--hor m-grid--root m-page">
    <div class="m-grid__item m-grid__item--fluid m-grid m-grid--hor m-login m-login--singin m-login--2 m-login-2--skin-1" id="m_login" style="background-image: url('{!! asset('assets/admin/media/img/bg/bg-1.jpg') !!}');">

        <div class="m-grid__item m-grid__item--fluid	m-login__wrapper">
            @include('admin.common.alerts')
            <div class="m-login__container">
                <div class="m-login__logo">
                    <a href="#">
                        <img src="{{imageUrl(asset('assets/admin/media/img/logos/logo.png'),343,80,1)}}">
                    </a>

                    @yield('content')
                </div>
            </div>
        </div>
    </div>
</div>


<script src="{{asset('assets/admin/vendors/base/vendors.bundle.js')}}" type="text/javascript"></script>
<script src="{{asset('assets/admin/js/scripts.bundle.js')}}" type="text/javascript"></script>
</body>
</html>